/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-115203-gbaf8651d56-20240513"
#endif /* AVUTIL_FFVERSION_H */
